apiVersion: v1
kind: Service
metadata:
    name: do-kubernetes-sample-app
    namespace: default
    labels:
        app: do-kubernetes-sample-app
spec:
    type: ClusterIP
    ports:
        - port: 80
          targetPort: http
          name: http
          protocol: TCP
          port: 80
          targetPort: 80
    externalIPs:
        - 64.225.83.145
    selector:
        app: do-kubernetes-sample-app